### PR TITLE
LPS-101154 Experiments sidebar components should be smaller as the figma design

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/dgarciasarai/liferay-portal/pull/112. [See changes here.](https://github.com/marcoscv-work/liferay-portal/compare/9efadf9aae6d~2...9efadf9aae6d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
