### PR TITLE
LPS-112620 Initial implementation of Clay Layout Tags

### PR DESCRIPTION
**Pull request by jbalsas**
Carry over from [LPS-112620 Adds initial clay:container tag #316](https://github.com/marcoscv-work/liferay-portal/pull/316).

**In this PR**

- [Implement clay:container tag](https://issues.liferay.com/browse/LPS-112620). Up to the final specs discussed at https://github.com/marcoscv-work/liferay-portal/pull/316#issuecomment-621905296 and based on [Define clay:container tag](https://issues.liferay.com/browse/LPS-112361)
- [Replace usages of aui:container with clay:container](https://issues.liferay.com/browse/LPS-112626). Replaces all direct usages of `aui:container` with `clay:container`.
- [Implement clay:row tag](https://issues.liferay.com/browse/LPS-112868) based on [Define clay:row tag](https://issues.liferay.com/browse/LPS-112363)
- [Replace usages of aui:row with clay:row](https://issues.liferay.com/browse/LPS-112870)
- [Replace usages of div class="row" with clay:row in JSPs](https://issues.liferay.com/browse/LPS-112872)
- [Implement clay:col tag](https://issues.liferay.com/browse/LPS-112869) based on [Define clay:col tag](https://issues.liferay.com/browse/LPS-112364)

## Pending

- [Replace usages of div class="container" with clay:container in JSPs](https://issues.liferay.com/browse/LPS-112628)
- [Replace usages of aui:col with clay:col](https://issues.liferay.com/browse/LPS-112871)
- [Replace usages of div class="col" with clay:col in JSPs](https://issues.liferay.com/browse/LPS-112873)

@marcoscv-work, @eduardoallegrini, can you please continue with the pending tasks from here? Please, check the similar `container` and `row` commits to see what needs to be done, since in some cases it's necessary to add some things to `build.gradle` or `init.jsp`. **We should be able to have those done today so we can send them tomorrow in time for the stabilization period.**

@wincent, I'd say we can forward this when green and try to squeeze this in and the rest before this stabilization period so we can catch any leftovers with enough time. Can you validate this, please?

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:stable

**Comment by jbalsas** [comment]
@marcoscv-work, please see the comment

> Your pull request was not tested because your repository has not set liferay-continuous-integration as a collaborator. See https://grow.liferay.com/share/Pull+Request+Tester+for+Liferay+Developers for more information.

Can you check what's going on here?

**Comment by jbalsas** [comment]
Will test and forward from https://github.com/wincent/liferay-portal/pull/245

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
