### PR TITLE
LPS-68736 avoid overlay of Add link on the portlet name

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
cc @brianwulbern

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44721. <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request closed without merging**
