### PR TITLE
LPS-92638 Add css to sidebar-title and sidebar-subitle

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74346. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
