### PR TITLE
LPS-114025 Fixing compilation problem: move variable so it iis accesible in the next col item

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:stable

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
The test failure on WebContentDisplay#SelectWebContent seems like a flaky or known issue https://issues.liferay.com/browse/LRQA-59070. What's interesting is that there isn't a web content that's available from the screenshot of the ci test...I wasn't able to reproduce this locally. I'll rerun the test on ci.

**Comment by john-co** [comment]
retesting locally with master snapshot bundle.

**Comment by john-co** [comment]
Not able to reproduce issue locally on master head: https://issues.liferay.com/browse/LRQA-59070?focusedCommentId=2167605&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2167605

Testray is backed up right now so will have to wait for results to trickle in for further analysis.

**Comment by marcoscv-work** [comment]
ci:forward

**Pull request closed without merging**
