### PR TITLE
LPS-88000 SF

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Just started reviewing :)

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66874. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
