### PR TITLE
LPS-111019 Do not override font-size here

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/victorg1991/liferay-portal/pull/230. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
