### PR TITLE
LPS-102594 Move css and update markup to fix <liferay-ui:search-container-column-user /> globally

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/1958. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
