### PR TITLE
IFI-455 Include header cell title for screen readers

### PR DESCRIPTION
**Pull request by wincent**
We had an empty table header sell which is confusing for screen reader users.

Test plan: In portal, go to left-hand sidebar -> Content -> Web Content, show table view. See screen-reader-only title in leftmost table header sell ("Selected Item").

Closes: https://issues.liferay.com/browse/IFI-455

screen_shot_2019-02-07_at_14_59_26_png

### CODE REVIEW

**Comment by wincent** [comment]
Note that I provided a description for this column rather than deleting the empty cell. I could also try deleting instead if that is considered a better approach.

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67786. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
