### PR TITLE
LPS-110753 Liferay sidebar is visible in print preview

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi @marcoscv-work ,

Can you have a look at this pull request, please?

Let us know whether you have any question about it.

Thanks.

Regards.

/cc @NemethNorbert

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/antonio-ortega/liferay-portal/pull/105. [See changes here.](https://github.com/marcoscv-work/liferay-portal/compare/203d3566a4df~1...203d3566a4df) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
