### PR TITLE
LPS-113002 - Add control-menu dark and light style abstraction

### PR DESCRIPTION
**Pull request by marcoscv-work**
Task to add the CSS required to use a new light control menu version:

To do this with the possibility to control variables, not by a CSS overwrite (possible future custom properties problems). I've created a style abstraction, for that we keep general box styles in the class: `control-menu-level-1` and I created:
`control-menu-level-1-dark` (added by default)
`control-menu-level-1-light`

How the abstraction works:

`control-menu-level-1-dark`:
image

`control-menu-level-1-light`
image

The task does not define hover states, so I've tried by adding the standard ones:
image

To use `control-menu-level-1-light` you will need to replace the class: `control-menu-level-1-dark`

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @marcoscv-work, do you want to send this to me when done so I can add what's missing?

**Pull request closed without merging**
