### PR TITLE
LPS-89096 Move the role="navigation" tag to the upper div

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc/ @antonio-ortega

**Comment by robertoDiaz** [comment]
Hey @marcoscv-work, (cc /@antonio-ortega)

Any uypdate on this??

A customer is waiting for a fix, and I'd like to provide a solution as similar to the final one as possible.

Thanks!!

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/1597. [See changes here.](https://github.com/marcoscv-work/liferay-portal/compare/b5638dabfc85~2...b5638dabfc85) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
