### PR TITLE
LPS-81239 Porygon Site Initializer

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/1373. [See changes here.](https://github.com/marcoscv-work/liferay-portal/compare/b6cb0d79df0b~1...b6cb0d79df0b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
