### PR TITLE
LPS-63581 - Apply CSS only to sidenav-menu

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:retest

**Comment by jkappler** [comment]
ci:retest

**Comment by marcoscv-work** [comment]
ci:retest

**Comment by jonmak08** [comment]
@kenjiheigel might have to take a look at the Poshi errors.

**Comment by jkappler** [comment]
@jonmak08, I tried sending myself the same PR. For me, it seems the poshi errors are completely unrelated to your changes

**Comment by jonmak08** [comment]
Hey @jkappler,

Yea, sometimes the PR tester will throw errors and we are not sure what is causing it.  I cc'd @kenjiheigel, so he can look at them.

I did not think the Poshi errors are related since they are failing in the DDM and our changes do not affect the DDM at all.

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal/pull/38046

**Pull request closed without merging**
