### PR TITLE
LPS-110007 - Replace input-editor with aui-input in blogs

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
@marcoscv-work everything is looking ok, but I'd need your help for the `.has-error` in the placeholder like we discussed over Slack

**Comment by julien** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/julien/liferay-portal/pull/235. [See changes here.](https://github.com/marcoscv-work/liferay-portal/compare/d570b1f6fbde~1...d570b1f6fbde) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
