### PR TITLE
LPS-70758 Show display for impersonated user who hasn't completed setup (fjord)

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey @SpencerWoo, @JorgeFerrer, we're looking into this since we don't think this is the right fix.

As far as we can tell, the `is_setupcomplete` was used thinking it was the equivalent to `PropsValues.SETUP_WIZARD_ENABLED`. This clearly isn't the case, so the right fix might be to use the intended variable instead of adding an `isImpersonated` check.

What do you think?

**Comment by SpencerWoo** [comment]
Hi @jbalsas 
The logic checks are all about when do we want to hide the default search and navigation portlets (and user icon).  

I am not sure what is the correct use case for hiding these portlets, but my thoughts are that `is_setup_complete` and `PropsValues.SETUP_WIZARD_ENABLED` are very different; the former is at the user level and the latter is a property affecting all (?) users.  Ultimately it comes down to whether `PropsValues.SETUP_WIZARD_ENABLED` is the proper controller for the visibility, and if it is then we should use it instead of `is_setup_complete` and `isImpersonated`.

That is to say, when `PropsValues.SETUP_WIZARD_ENABLED` is false do we want to hide the default Search and Navigation portlet for all its users?

**Comment by marcoscv-work** [comment]
Hey guys,

The initial proposal was check when the setup wizard is complete, only when it is complete we should show navigation / user.
We used is_setup_complete thinking this was the correct way but it looks like not.
Right now we are validating if we can use propsUtil.get('setup.wizard.enabled')

The only theme should have this validation is classic, I will remove it from other themes.

**Comment by JorgeFerrer** [comment]
Thanks @SpencerWoo for finding out about this problem.

Thanks @jbalsas and @marcoscv-work for working out the optimal solution.

**Comment by jbalsas** [comment]
Actually, after further investigation, it seems like that check is pointless, as hinted by @drewbrokke in the [original comment](https://github.com/JorgeFerrer/liferay-portal/pull/816#issue-219122955). We'll probably proceed to completely remove the check from all themes.

**Comment by jbalsas** [comment]
After some more thought... it looks like what we're actually trying to avoid is to show the navigation and search portlets when the user is asked to change password or the reminder query...

**Comment by SpencerWoo** [comment]
@jbalsas That makes a lot of sense because we're hiding the portlets when the user hasn't completed the setup.  

If is_setup_complete is intended behavior it makes sense to me to use the isImpersonated() check.  However because this is closed I'm assuming we plan on removing the check and hiding the portlets a different way?  Will watch LPS-70758 for updates.

Thanks all.

**Comment by jbalsas** [comment]
Hey @SpencerWoo, I don't think `isImpersonated` is the right thing to do. A theme shouldn't need to be aware of such scenarios. On top of that, as far as I can tell, there are [more scenarios](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/struts/PortalRequestProcessor.java#L719-L726) other than that one and [more cases](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/struts/PortalRequestProcessor.java#L728-L777) that will probably cause inconsistencies.

We need to figure out the proper way to represent that state in the application so the themes can pick it up. @izaera is looking into it

**Pull request closed without merging**
