### PR TITLE
LPS-85153 buildLang

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test

**Comment by boton** [comment]
Add a title to the simulationDeviceIframe

image

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67742. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
