### PR TITLE
LPS-76586 Update to Clay v2.0.0-beta.5

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-76586

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
ci:reopen

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/930. [See changes here.](https://github.com/marcoscv-work/liferay-portal/compare/f416d4a4d423~2...f416d4a4d423) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
