### PR TITLE
LPS-114056 Fix variable scope in redirect

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
Hey @slnn! we are not sure about the performance of this change:
https://github.com/marcoscv-work/liferay-portal/pull/336/commits/91f108d10a8450934ff52c943deb3f6336e56ff7

Is it possible to test it?

**Comment by slnn** [comment]
Hi @marcoscv-work 

I can check the performance the specify commit https://github.com/marcoscv-work/liferay-portal/commit/91f108d10a8450934ff52c943deb3f6336e56ff7 you mentioned, but I will run a performance test with this pull to see if it caused any performance regression in our daily monitor performance test firstly, if no regression appeared with the full pull's change, do you still want me to check the performance about the specify commit?

Thanks
Lily

**Comment by jbalsas** [comment]
Hey @slnn, forget about this for now, let's focus on our other set of tests. Once those are okay we can safely make the changes in `ratings-taglib`. We'll drop them for now.

@marcoscv-work, @boton, please drop the changes on `ratings-taglib`. We're already working on testing performance in a separate thread.

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/2203. [See changes here.](https://github.com/marcoscv-work/liferay-portal/compare/fa83ceef7aef~5...fa83ceef7aef) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Resend here:
https://github.com/jbalsas/liferay-portal/pull/2203

**Pull request closed without merging**
