### PR TITLE
LPS-74575 Shortcut icon does not display for sites with long names

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by dustinryerson** [comment]
Hi @marcoscv-work, any update on this review?

**Comment by marcoscv-work** [comment]
Hey guys,

We are studying how to apply these changes. Since Clay CSS was implemented in master much markup will change, Card included.

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/1131. [See changes here.](https://github.com/marcoscv-work/liferay-portal/compare/5dc82c51e700~1...5dc82c51e700) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
