### PR TITLE
LPS-112620 Adds initial clay:container tag

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @marcoscv-work, @eduardoallegrini, I've put this quickly together so we can have a better sense of progress and make pragmatic decisions based on real usage in DXP.

This PR adds support for the following:

```html
<clay:container />
<clay:container cssClass="foo" />
<clay:container fluid="<%= false %>" />
<clay:container id="container1" />
<clay:container fluid="<%= false %>" id="container2" />
<clay:container cssClass="foo" id="container1" />
<clay:container cssClass="foo" fluid="<%= false %>" id="container2" />
```

This is the current state of tasks in the epic:
- [**Define clay:container tag**](https://issues.liferay.com/browse/LPS-112361). The definition task. Let's keep it open while we understand better the requirements here and document our findings back there.
- [**Implement clay:container tag**](https://issues.liferay.com/browse/LPS-112620). This PR. We can add on top based on the following tasks.
- [**Replace usages of aui:container with clay:container**](https://issues.liferay.com/browse/LPS-112626)
- [**Replace usages of div class="container" with clay:container**](https://issues.liferay.com/browse/LPS-112628)

My suggestion would be to take this PR and each of you take one of the tasks I just created and apply it globally. If you find usages that are not accounted for, then we talk it through, add the necessary APIs and continue until those are done.

That way, we move forward in a practical way and make sure we're providing real value to our existing developers and code-base.

Please, coordinate with @wincent and @esanzp if necessary! 😘

### CODE REVIEW

**Comment by wincent** [comment]
Just a question from a JSP noob:

```jsp
<clay:container fluid="<%= false %>" />
```

In liferay-portal, I see that interpolating `false` or `true` in this way is very common (> 1,000 hits in a crude search), but I also see tags that use a string and presumably do some kind of coercion on it; eg.

```jsp
<aui:input name="useSignature" type="hidden" value="false" />
```

That's way less common (only a couple dozen hits). I gather that we should do this exactly the way you've done it, @jbalsas, in the name of consistency. But just wanted to gut check that with you because doing it without the interpolation feels a bit more light-weight.

**Comment by jbalsas** [comment]
Hey @wincent, yeah, I'm unsure about what's the proper etiquette here... I even remember we used to have some cases of `value="<%= Boolean.TRUE %>"`... I think it depends on the signature and we should be able to coerce here, but we can get this through a proper expert later :)

**Comment by edalgrin** [comment]
Just started reviewing :)

**Comment by pat270** [comment]
Could we name the `fluid` attribute to something else? I would expect `container-fluid` instead of `container-fluid container-fluid-max-xl`.

**Comment by jbalsas** [comment]
Hey @pat270,

> Could we name the fluid attribute to something else? I would expect container-fluid instead of container-fluid container-fluid-max-xl.

Do you have any specific proposal? @marcoscv-work? @eduardoallegrini? 

In `aui:container`, `fluid="true"` indeed just adds `container-fluid`. Based on the changes and usages at https://github.com/eduardoallegrini/liferay-portal/pull/64, this is our most used approach. Still waiting to see the direct usages we have before committing to a final API, but I want it based on real data.

@marcoscv-work, @eduardoallegrini, please work on [Replace usages of div class="container" with clay:container](https://issues.liferay.com/browse/LPS-112628) so we can get a real sense on what else we need here. We can discuss the changes and I can adjust the tag for you, but I need you to provide the data and samples we need to make good decisions.

**Comment by jbalsas** [comment]
I've push-forced some updates and cherry-picked https://github.com/eduardoallegrini/liferay-portal/pull/64 on top so we can start seeing the API take shape.

Things I've done since yesterday's PR:
- Deprecated `aui:container` in favor of `clay:container`
- Removed padding attribute for now. We can add it later.
- No more duplicated classes

From now on, using `<clay:container cssClass="foo bar container-fluid foo container-fluid-max-xl bar">` will now generate

```html
<div class="container-fluid container-fluid-max-xl foo bar">
```

instead of

```html
<div class="container-fluid container-fluid-max-xl foo bar container-fluid foo container-fluid-max-xl bar">
```

@marcoscv-work, @eduardoallegrini, please, stack some additional update changes here so we can make a final decision on how to bring the padding/fluid or other attributes into the mix.

Thanks!

/cc @wincent

**Comment by edalgrin** [comment]
> Could we name the fluid attribute to something else? I would expect container-fluid instead of container-fluid container-fluid-max-xl.

> Do you have any specific proposal? @marcoscv-work? @eduardoallegrini?

As @marcoscv-work  said in the [layout-taglib-container-documentation](https://docs.google.com/document/d/1ry-zdKBmM8x-Y3x1O4jvqzLKmeEY23INd32_-aEat84/edit#), we could leave `.container-fluid.container-fluid-max-xl` as default and add the property `wrapped` with the values:
- `sm` - print `.container-fluid.container-fluid-max-sm`
- `md` - print `.container-fluid.container-fluid-max-md`
- `lg` - print `.container-fluid.container-fluid-max-lg`
- `always` - print `.container`

In this way we won't need the `wrapped-sm`, `wrapped-md`, `wrapped-lg` variations

**Comment by jbalsas** [comment]
So... let's see if we can get a proper definition. Can you validate if the following combination produces the expected output classes? I'm not sure about the naming, though... `wrapped` doesn't make a lot of sense in my mind... could you explain what it does so we can find if `wrapped` is the proper name for it?

fluid | wrapped | output classes
--- | --- | ---
| [`true`]  | [`xl`]  | `container-fluid container-fluid-max-xl`
| [`true`]  | `breakpoint` | `container-fluid container-fluid-max-${breakpoint}`
| [`true`] | `false` | `container-fluid`
| `false` | [`xl`]  | `container container-max-xl`
| `false` | `breakpoint` | `container container-max-${breakpoint}`
| `false` | `false` | `container`

**Comment by edalgrin** [comment]
I was thinking about removing `fluid` in favor of `wrapped` 

```
// INPUT
<clay:container>...</clay:container>
// OUPUT
<div class="container-fluid container-fluid-max-xl">...</div>
```

```
// INPUT
<clay:container wrapped="sm">...</clay:container>
// OUPUT
<div class="container-fluid container-fluid-max-sm">...</div>
```

```
// INPUT
<clay:container wrapped="md">...</clay:container>
// OUPUT
<div class="container-fluid container-fluid-max-md">...</div>
```

```
// INPUT
<clay:container wrapped="lg">...</clay:container>
// OUPUT
<div class="container-fluid container-fluid-max-lg">...</div>
```

```
// INPUT
<clay:container wrapped="always">...</clay:container>
// OUPUT
<div class="container">...</div>
```

**Comment by jbalsas** [comment]
That could work... would it make sense to call it ‘wrapper’ rather than ‘wrapped’?

@marcoscv-work, @pat270, would this satisfy your expectations?

**Comment by eduardoallegrini** [comment]
Just started reviewing :)

**Comment by pat270** [comment]
@jbalsas @eduardoallegrini @marcoscv-work how about `size` or `width` instead of `wrapped`?

**Comment by jbalsas** [comment]
Hey @pat270, what would be the `size` or `width` value that makes it 100%? since we'll be adding classes, how do we encode such a thing? `none`? `full`?

**Comment by kresimir-coko** [comment]
@jbalsas I agree with @pat270 that `wrapped` is a bit confusing, when the output expected value isn't a boolean, `size` or `width` make more sense to me. 

> what would be the size or width value that makes it 100%?
### Size
I propose `<clay:container size="full-width">`. `full-width` is very descriptive, at least IMO. I believe that Bootstrap uses `size` in context of those values(`md`, `lg`, etc).
### Width
If going with `width`, maybe go with `<clay:container width="full">` since width is implied. 

I'll leave the intricacies of classes to @pat270 as he is an expert in that department.

**Comment by marcoscv-work** [comment]
Hey guys, yes, Bootstrap uses "screen sizes" as a reference with screens breakpoints, so `sizes` could be a good option, personally I like width because for me it looks great: `width="full"`

**Comment by jbalsas** [comment]
So, @marcoscv-work, @eduardoallegrini, @pat270, I've push-forced some changes based on this so now what we have is:

```html
<clay:container />

    |> <div class="container-fluid container-fluid-xl">...</div>

<clay:container className="foo" />

    |> <div class="container-fluid container-fluid-xl foo">...</div>

<clay:container size="md" />

    |> <div class="container-fluid container-fluid-md">...</div>

<clay:container size="<%= null %>" />

    |> <div class="container">...</div>

<clay:container className="foo" size="<%= null %>" />

    |> <div class="container foo">...</div>
```

I changed `cssClass` to `className` to achieve some symmetry with React `className` if Brian allows it...

/cc @wincent

**Comment by marcoscv-work** [comment]
With those changes. Could we get only the `container-fluid`? is this possible?

`<div class="container-fluid">...</div>`

**Comment by jbalsas** [comment]
Right now there isn’t. You need to tell me how you’d expect to get that output either with the size attribute or with others

**Comment by marcoscv-work** [comment]
> Right now there isn’t. You need to tell me how you’d expect to get that output either with the size attribute or with others

maybe by `size="fluid"`

Output:
`<div class="container-fluid">...</div>`

Right now we get a breakpoint size by classes: class=`"container-fluid container-fluid-XX"`
Maybe in the future, it is a merge of different classes names, but I think we will always need a container full fluid, right now `class="container-fluid"`

**Comment by jbalsas** [comment]
> maybe by size="fluid"

Doesn't make a lot of sense... are there equivalents to `container-fluid-max-xl` without the `fluid` part? If you need this, then maybe we need `size` and then `type=[fluid|fixed]` or `fluid=[true|false]` to represent this.

**Comment by marcoscv-work** [comment]
We have an agreement:

We don't need only a `class="container"`, we will use instead of that `class="container-fluid container-fluid-max-xl"`

So it will be:

```html
<clay:container />

    |> <div class="container-fluid container-fluid-max-xl">...</div>

<clay:container className="foo" />

    |> <div class="container-fluid container-fluid-max-xl foo">...</div>

<clay:container size="md" />

    |> <div class="container-fluid container-fluid-max-md">...</div>

<clay:container size="<%= null %> or none" />

    |> <div class="container-fluid">...</div>

<clay:container className="foo" size="<%= null %>" />

    |> <div class="container-fluid foo">...</div>
```

**Comment by jbalsas** [comment]
Ok, clean break at https://github.com/marcoscv-work/liferay-portal/pull/317, I'll update the description and work done over there so we can forward it and build on top.

**Pull request closed without merging**
