### PR TITLE
LPS-96452 fix for user icon overlaps margin

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74288. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
