### PR TITLE
LPS-112988 Replace markup and refactor js

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/carloslancha/liferay-portal/pull/265. [See changes here.](https://github.com/marcoscv-work/liferay-portal/compare/c207393d1516~3...c207393d1516) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
