### PR TITLE
LPS-114881 Adapt the style of the product-menu to the new global-app-menu

### PR DESCRIPTION
**Pull request by edalgrin**
I made the minimum changes necessary to obtain the required result and I tried to clean a little bit the code in the same section (list-group) removing the unused variables and reordering the modifiers.

The file is still pretty messy but since we need this ASAP and we are planning to introduce a new product menu, I think we shouldn't spend more time on it.

I checked several times and these changes don't seem to be causing any breaking change, but if you could check as well it would be better 😄 

Thank you!

image

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
@marcoscv-work, is this still pending?

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:stop

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/marcoscv-work/liferay-portal/pull/341. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
PR reviewed and rebase here:
https://github.com/marcoscv-work/liferay-portal/pull/341

**Pull request closed without merging**
