### PR TITLE
Lps 134590

### PR DESCRIPTION
**Pull request by ethib137**
Hey @marcoscv-work, just wanted to share this with you while we wait for the first pull to get into master. After that's in I'll rebase and send a new pull to Eduardo. 

I really appreciated your comments. It's pretty cool how much code was reduced by using the CSS Custom Properties in buttons. If you have any additional comments, please do share.

### CODE REVIEW

**Comment by ethib137** [comment]
FYI @epgarcia

**Comment by marcoscv-work** [comment]
I'm going to be busy until next Monday, so if needed feel free to go ahead without me ;-) !

(it looks great!!!)

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Wow! it looks great! just some appreciations:

About the naming, probably add "Dialect" to the token group naming can be a little bit confusing:

image

I mean, the rest of the token will be based on the Dialect design as well, so we could add "Dialect" to all groups

About files, we can make a file compare with styled, if the file is the same. we can remove it, I've seen the pattern on files like:

https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/portlet/_portlet_decorator.scss
`_spec.scss`
`_topper.scss`
etc..

Thanks @ethib137 !

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/1039. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
One more thing, there are color properties with 8 RGB values:

"defaultValue": "#FFFFFF80"

:-D

**Comment by marcoscv-work** [comment]
Buttons in classic:
image


Buttons in solutions:
image

**Comment by ethib137** [comment]
> Wow! it looks great! just some appreciations:
> 
> About the naming, probably add "Dialect" to the token group naming can be a little bit confusing:
> 
> image
> 
> I mean, the rest of the token will be based on the Dialect design as well, so we could add "Dialect" to all groups
> 

Thanks @marcoscv-work 
For the naming, I don't want to change the names of the tokens that are also included in classic, since one of the goals is to change as little as possible. Maybe the best option would be to not namespace custom categories. So dialect-actions could just be actions.

> About files, we can make a file compare with styled, if the file is the same. we can remove it, I've seen the pattern on files like:
> 
> https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/portlet/_portlet_decorator.scss
> `_spec.scss`
> `_topper.scss`
> etc..
> 
> Thanks @ethib137 !

For the files, I think this should be solved by the work @epgarcia is doing, creating a way to copy files from classic at build. This will reduce duplication, so that the only duplicate files will be ones that we have to modify in some way.

**Comment by ethib137** [comment]
> One more thing, there are color properties with 8 RGB values:
> 
> "defaultValue": "#FFFFFF80"
> 
> :-D

Should we still not use 8 digit hexcodes? I thought it was now okay due to us no longer supporting IE11: https://caniuse.com/css-rrggbbaa

**Comment by marcoscv-work** [comment]
Recently I had problems with some tests for that reason and on the other hand, the color picker works with 6 hex color format so maybe the combination of sometimes 8 and sometimes 6 is a UX strange combination, anyway I totally agree to try to go ahead with it and leave IE behind :-P

**Comment by marcoscv-work** [comment]
Now I see: https://issues.liferay.com/browse/LEXI-1201
:-P

**Comment by ethib137** [comment]
> Buttons in classic:
> image
> 
> Buttons in solutions:
> image

This resulted from not having the btn-solid class added to these buttons. I had written the styles so that one of the classes btn-solid, btn-ghost, btn-borderless, or btn-round was always required. It probably makes more sense to add the btn-solid styles as a default even when only the btn class is present. This should reduce the chance of having an unstyled button show up. Thanks.

**Pull request closed without merging**
