### PR TITLE
LPS-114881 Adapt the style of the product-menu to the new global-app-menu

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
@John-Co could you take a took, I'm not sure if relevant file is related

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

It looks like the same error is affecting other PRs. I believe the two tests should be disabled so it doesn't affect others. -> Found existing ticket: https://issues.liferay.com/browse/LRQA-59331 

The quarantine was merged a couple hours ago https://github.com/brianchandotcom/liferay-portal/pull/89907 and is now in upstream.

Also since there's no unique failures from the ci bot message, running `ci:forward` should work.

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
